apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: bestbuy
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: bestbuy
spec:
  serviceName: mongo
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: bestbuy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: ahmedboudouh/bestbuy-product-service:latest
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: PRODUCT_SERVICE_PORT
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: MONGO_URI
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: bestbuy
spec:
  selector:
    app: product-service
  ports:
    - port: 4000
      targetPort: 4000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: bestbuy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ahmedboudouh/bestbuy-order-service:latest
          ports:
            - containerPort: 4001
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: ORDER_SERVICE_PORT
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: MONGO_URI
            - name: SERVICE_BUS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: bestbuy-secrets
                  key: SERVICE_BUS_CONNECTION_STRING
            - name: SERVICE_BUS_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: SERVICE_BUS_QUEUE_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: bestbuy
spec:
  selector:
    app: order-service
  ports:
    - port: 4001
      targetPort: 4001
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-front
  namespace: bestbuy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-front
  template:
    metadata:
      labels:
        app: store-front
    spec:
      containers:
        - name: store-front
          image: ahmedboudouh/bestbuy-store-front:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: STORE_FRONT_PORT
            - name: PRODUCT_API_BASE
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: PRODUCT_API_BASE
            - name: ORDER_API_BASE
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: ORDER_API_BASE
---
apiVersion: v1
kind: Service
metadata:
  name: store-front
  namespace: bestbuy
spec:
  selector:
    app: store-front
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-admin
  namespace: bestbuy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-admin
  template:
    metadata:
      labels:
        app: store-admin
    spec:
      containers:
        - name: store-admin
          image: ahmedboudouh/bestbuy-store-admin:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: STORE_ADMIN_PORT
            - name: PRODUCT_API_BASE
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: PRODUCT_API_BASE
            - name: ORDER_API_BASE
              valueFrom:
                configMapKeyRef:
                  name: bestbuy-config
                  key: ORDER_API_BASE
---
apiVersion: v1
kind: Service
metadata:
  name: store-admin
  namespace: bestbuy
spec:
  selector:
    app: store-admin
  ports:
    - port: 80
      targetPort: 3001
  type: LoadBalancer
